spring:
  thymeleaf:
    cache: false
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:/tmp/
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
